### ISSUE TITLE
Which cpp to use?

### ISSUE THREAD

**Issue by rafael2k** [hintron/8086-toolchain#11]
Is it correct I should use a cpp before c86, right? Which one to use?

**Comment by hintron** [comment]
Yes. `c86` does not have a built-in C pre-processor, so it doesn't understand macros. So you need to use `cpp` (GNU C Preprocessor) first to process the macros in your code. (It appears that `gcc` uses `cpp` automatically under the hood when compiling C/C++ code).

Here's the workflow (from https://hintron.github.io/8086-toolchain/current/slides/pdf/set1.pdf):
![image](https://github.com/user-attachments/assets/9eab781d-7269-4453-afb2-b6c59d78e02b)

You can generally use any `cpp` you can find, and it should work for most C code. You can also look into these `cpp` options if you need to control the ISO C standard you want to follow: `-std=c90, -std=c99, -std=c11, -std=c17`. But I've never needed to specify that for simple macro expansion.

**Comment by rafael2k** [comment]
I'm using dev86 cpp, which I ported to run natively on 8086. Seems all good indeed. 

Thanks!
