### ISSUE TITLE
Missing c86manual.txt?

### ISSUE THREAD

**Issue by ghaerr** [hintron/8086-toolchain#13]
Hello @hintron,

Nice repo you have here!

I notice in the gh-pages branch, the [ECEn 425 Online Resources](https://hintron.github.io/8086-toolchain/stable/resources.html) link has a [C86 Compiler Features](https://hintron.github.io/8086-toolchain/stable/labs/C86Features.html) page that has a [bad link](https://hintron.github.io/8086-toolchain/stable/labs/c86manual.txt) to a C86 Manual, toolchain-8086/stable/labs/c86manual.txt.

Do you happen to have a copy of that somewhere? I can't seem to find it anywhere on your GitHub.io site. I am currently helping to evaluate the C86 compiler and its assembler for its suitability to be used as a [self-hosted C compiler](https://github.com/ghaerr/elks/issues/2112)  for the [ELKS Project](https://github.com/ghaerr/elks). It would be really helpful to be able to read about what the C86 compile does and does not do.

Thank you!

**Comment by hintron** [comment]
Let me take a look... When the class website went down, I had to scrape together the contents from Wayback Machine and from my own personal TA files, but some things might have been permanently lost. Hopefully I can find that doc somewhere.

**Comment by hintron** [comment]
I do not have it, but let me ask my professor to see if he still has a copy of it.

**Comment by hintron** [comment]
In the meantime, I added what I think is the missing manual in commit https://github.com/hintron/8086-toolchain/commit/f9182e531c311cb8eebb73b927f35ecb8c834fcd. See https://hintron.github.io/8086-toolchain/stable/labs/c86manual.txt.

If my professor gets back to me with his copy of the manual, I'll compare and see if there are any differences. But I suspect it will be the same.

**Comment by ghaerr** [comment]
Thanks @hintron, this really helps!

**Comment by hintron** [comment]
You can thank @bocke for finding this copy!

My professor did not keep a copy of the manual, but he also didn't recall making any special modifications to it (if he did, then he probably wouldn't have described caveats regarding the manual in  https://hintron.github.io/8086-toolchain/stable/labs/C86Features.html - he would have just updated the manual). I also never recalled referencing a c86 manual that had any class-specific custom changes in it when I took/TA'd the class. 

Owing to the fact that the manual Bojan found was almost the exact same size as indicated on the class webpage, and that it was also a text file as indicated on the class webpage (and also looked vaguely familiar), I assume it is roughly the same file. At this point, it's the best we got anyways :)

**Comment by ghaerr** [comment]
Thanks for the background @hintron. And yes @bocke has been skillfully digging up all kinds of stuff relating to the history of C86. Thanks @bocke!
